# Generated by Django 5.1.4 on 2024-12-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=8),
            preserve_default=False,
        ),
    ]
